export const data =[
    {
        id: "id1",
        name: "arbok",
        imageUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full//005.png",
        desc: "This is Pokemon arbok",
        Height : "200 cm",
        Weight: "100 kg",
        Stat : {
                hp : "80",
                attack : "82",
                defense : "83",
                special_attack : "100",
                special_defense : "100",
                speed : "80",
               },
    },

    {
        id: "id2",
        name: "arcanine",
        imageUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full//071.png",
        desc: "This is Pokemon arcanine",
        Height : "210 cm",
        Weight: "110 kg",
        Stat : {
                hp : "81",
                attack : "83",
                defense : "84",
                special_attack : "110",
                special_defense : "110",
                speed : "81",
               },
    },
    {
        id: "id3",
        name: "blastoise",
        imageUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full//105.png",
        desc: "This is Pokemon blastoise",
        Height : "220 cm",
        Weight: "120 kg",
        Stat : {
                hp : "82",
                attack : "84",
                defense : "85",
                special_attack : "120",
                special_defense : "130",
                speed : "86",
               },
    },
    {
        id: "id4",
        name: "bulbasaur",
        imageUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full//141.png",
        desc: "This is Pokemon bulbasaur",
        Height : "120 cm",
        Weight: "140 kg",
        Stat : {
                hp : "42",
                attack : "54",
                defense : "65",
                special_attack : "55",
                special_defense : "100",
                speed : "40",
               },
    },
    {
        id: "id5",
        name: "charmander",
        imageUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full//322.png",
        desc: "This is Pokemon charmander",
        Height : "66 cm",
        Weight: "135 kg",
        Stat : {
                hp : "50",
                attack : "154",
                defense : "120",
                special_attack : "180",
                special_defense : "149",
                speed : "90",
               },
    },
    {
        id: "id6",
        name: "charmeleon",
        imageUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full//337.png",
        desc: "This is Pokemon charmeleon",
        Height : "100 cm",
        Weight: "113 kg",
        Stat : {
                hp : "80",
                attack : "129",
                defense : "70",
                special_attack : "135",
                special_defense : "80",
                speed : "60",
               },
    },
    {
        id: "id7",
        name: "diglett",
        imageUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full//637.png",
        desc: "This is Pokemon diglett",
        Height : "118 cm",
        Weight: "6 kg",
        Stat : {
                hp : "20",
                attack : "30",
                defense : "40",
                special_attack : "40",
                special_defense : "50",
                speed : "20",
               },
    },
    {
        id: "id8",
        name: "dugtrio",
        imageUrl: "../public/image/arbok.png",
        desc: "This is Pokemon dugtrio",
        Height : "66 cm",
        Weight: "123 kg",
        Stat : {
                hp : "40",
                attack : "120",
                defense : "134",
                special_attack : "132",
                special_defense : "154",
                speed : "43",
               },
    },
    {
        id: "id9",
        name: "ekans",
        imageUrl: "../public/image/arbok.png",
        desc: "This is Pokemon ekans",
        Height : "66 cm",
        Weight: "134 kg",
        Stat : {
                hp : "87",
                attack : "198",
                defense : "143",
                special_attack : "200",
                special_defense : "149",
                speed : "90",
               },
    },
    {
        id: "id10",
        name: "exeggutor",
        imageUrl: "../public/image/arbok.png",
        desc: "This is Pokemon exeggutor",
        Height : "123 cm",
        Weight: "165 kg",
        Stat : {
                hp : "80",
                attack : "134",
                defense : "154",
                special_attack : "180",
                special_defense : "149",
                speed : "89",
               },
    },
    {
        id: "id11",
        name: "flareon",
        imageUrl: "../public/image/arbok.png",
        desc: "This is Pokemon flareon",
        Height : "110 cm",
        Weight: "159 kg",
        Stat : {
                hp : "94",
                attack : "132",
                defense : "137",
                special_attack : "140",
                special_defense : "149",
                speed : "55",
               },
    },
    {
        id: "id12",
        name: "frarow",
        imageUrl: "../public/image/arbok.png",
        desc: "This is Pokemon frarow",
        Height : "123 cm",
        Weight: "99 kg",
        Stat : {
                hp : "77",
                attack : "134",
                defense : "160",
                special_attack : "140",
                special_defense : "179",
                speed : "110",
               },
    },
    {
        id: "id13",
        name: "gengar",
        imageUrl: "../public/image/arbok.png",
        desc: "This is Pokemon gengar",
        Height : "75 cm",
        Weight: "66 kg",
        Stat : {
                hp : "50",
                attack : "54",
                defense : "20",
                special_attack : "80",
                special_defense : "49",
                speed : "30",
               },
    },
    {
        id: "id14",
        name: "golduck",
        imageUrl: "../public/image/arbok.png",
        desc: "This is Pokemon golduck",
        Height : "144 cm",
        Weight: "129 kg",
        Stat : {
                hp : "70",
                attack : "129",
                defense : "140",
                special_attack : "130",
                special_defense : "149",
                speed : "60",
               },
    },
    {
        id: "id15",
        name: "hoppip",
        imageUrl: "../public/image/arbok.png",
        desc: "This is Pokemon hoppip",
        Height : "145 cm",
        Weight: "115 kg",
        Stat : {
                hp : "70",
                attack : "94",
                defense : "80",
                special_attack : "110",
                special_defense : "149",
                speed : "140",
               },
    },
    {
        id: "id16",
        name: "hypno",
        imageUrl: "../public/image/arbok.png",
        desc: "This is Pokemon hypno",
        Height : "166 cm",
        Weight: "185 kg",
        Stat : {
                hp : "99",
                attack : "154",
                defense : "120",
                special_attack : "180",
                special_defense : "149",
                speed : "90",
               },
    }
]